### ISSUE TITLE
Storage path not automatically created

### ISSUE THREAD

**Issue by wackerl91** [wackerl91/script.luna#110]
- Luna Version: 0.7.0-rc1
- nVidia GeForce Experience Version: -
- Moonlight Embedded Version: -
- OSMC Version: 2016.11-1

**Expected Behaviour:**
Storage path should be created if it doesn't exist before it is used (for example on new installations). 

**Actual Behaviour:**
It's not checked before its first use, preventing the start of the addon until the folder is manually created.

**Comment by wackerl91** [comment]
```
20:02:27 59.410374 T:1260123120 ERROR: Exception in thread Thread-5:
Traceback (most recent call last):
File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
self.run()
File "/usr/lib/python2.7/threading.py", line 763, in run
self.__target(*self.__args, **self.__kwargs)
File "/home/osmc/.kodi/addons/script.luna/resources/lib/core/updateservice.py", line 56, in check_for_update
update_storage.sync()
File "/home/osmc/.kodi/addons/script.luna/resources/lib/storageengine/storage.py", line 53, in sync
fileobj = open(tempname, 'wb' if self.file_format == 'pickle' else 'w')
IOError: [Errno 2] No such file or directory: '/home/osmc/.kodi/userdata/addon_data/script.luna/.storage/update.tmp
```
